### ISSUE TITLE
ERD For Query Exercises

### ISSUE THREAD

**Issue by swanandp** [swanandp/sharp-knives-pgw#2]
![PG-Masterclass-Exercise-ERD](https://user-images.githubusercontent.com/90904/93637536-625ff580-fa13-11ea-974e-fa4b23928a5a.png)

**Comment by Indrajitnaiya09** [comment]
@swanandp what is the issue? I'm not getting. This problem statement we solved in the class!! right?

**Comment by swanandp** [comment]
No issue. I just needed to upload the image somewhere.
